#!/bin/zsh
source ~/.zshrc

set -e

# Which branch are we on
branch="$(git rev-parse --abbrev-ref HEAD)"

# If we are on master
if [ $branch = "master" ]; then

    # Behat
    printf "\e[1;33mpre-push:\e[0m: Behat\n"
    behat
    if [ $? -eq 0 ]
    then
        printf "\e[1;32mSuccessful:\e[0m Behat\n"
    else
        printf "\e[1;31mError:\e[0m Behat\n"
        exit 1
    fi

    printf "\n\n=========================================\n"

    # Phpunit
    printf "\e[1;33mpre-push:\e[0m: PhpUnit\n"
    phpunit
    if [ $? -eq 0 ]
    then
        printf "\e[1;32mSuccessful:\e[0m PhpUnit\n"
    else
        printf "\e[1;31mError:\e[0m PhpUnit\n"
        exit 1
    fi
fi

exit 0
