#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check typescript errors
yarn run type:check

# check js linting errors
yarn run lint:js:check

# check formatting errors
yarn run format:check

# check wasm linting errors
yarn run lint:wasm:check

# run tests
yarn run test
