#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check typescript errors
yarn run type:check

# check js linting errors
yarn run lint:js:check || (echo "run 'yarn run lint:js' to fix any auto-fixable linting errors"; false);

# check formatting errors
yarn run format:check || (echo "run 'yarn run format' to fix any formatting errors"; false);

# check wasm linting errors
yarn run lint:wasm:check || (echo "run 'yarn run lint:wasm' to fix rust linting errors"; false);

# run tests
yarn run test
